version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.10
  # slack: circleci/slack@3.4.2
  # node: circleci/node@3.0.0
# jobs:
#   slack_notify:
#     executor:
#       name: node/default
#     steps:
#       - slack/notify:
#           color: "#42e2f4"
#           mentions: "UNCPHM6EP,"
#           message: A custom message to notify the channel about the latest build
#       - slack/status:
#           mentions: "UNCPHM6EP"
#       - slack/status:
#           fail_only: true
#           mentions: "UNCPHM6EP"
# executors:
#   default:
#       machine:
#           docker_layer_caching: true
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          # executor: default
          name: build-and-push-image-api-dev
          dockerfile: Dockerfile-Api
          create-repo: true
          repo: soccerbee-api
          tag: "dev"
          filters:
            branches:
              only: develop

      - aws-ecs/deploy-service-update:
          name: deploy-service-update-api-dev
          requires:
            - build-and-push-image-api-dev    
          family: api-dev
          cluster-name: "soccerbee"
          container-image-name-updates: "container=api-dev,tag=dev"
          filters:
            branches:
              only: develop
      
      
      - aws-ecr/build-and-push-image:
          name: build-and-push-image-api-prod
          dockerfile: Dockerfile-Api
          create-repo: true
          repo: soccerbee-api
          tag: "prod"
          filters:
            branches:
              only: master

      - aws-ecs/deploy-service-update:
          name: deploy-service-update-api-prod
          requires:
            - build-and-push-image-api-prod    
          family: api-prod
          cluster-name: "soccerbee"
          container-image-name-updates: "container=api-prod,tag=prod"
          filters:
            branches:
              only: master
              
      - aws-ecr/build-and-push-image:
          name: build-and-push-image-admin-dev
          dockerfile: Dockerfile-Admin
          create-repo: true
          repo: soccerbee-admin
          tag: "dev"
          filters:
            branches:
              only: develop

      - aws-ecs/deploy-service-update:
          name: deploy-service-update-admin-dev
          requires:
            - build-and-push-image-admin-dev    
          family: admin-dev
          cluster-name: "soccerbee"
          container-image-name-updates: "container=admin-dev,tag=dev"
          filters:
            branches:
              only: develop

      - aws-ecr/build-and-push-image:
          name: build-and-push-image-admin-prod
          dockerfile: Dockerfile-Admin
          create-repo: true
          repo: soccerbee-admin
          tag: "prod"
          filters:
            branches:
              only: master
      
      - aws-ecs/deploy-service-update:
          name: deploy-service-update-admin-prod
          requires:
            - build-and-push-image-admin-prod    
          family: admin-prod
          cluster-name: "soccerbee"
          container-image-name-updates: "container=admin-prod,tag=prod"
          filters:
            branches:
              only: master
  # slack_notification:
  #   jobs:
  #     - slack_notify

      # - aws-ecr/build-and-push-image:
      #     name: build-and-push-image-batch-dev
      #     dockerfile: Dockerfile-Batch
      #     create-repo: true
      #     repo: soccerbee-batch
      #     tag: "dev"
      #     filters:
      #       branches:
      #         only: develop