server:
  error:
    include-stacktrace: never

spring:
  profiles:
    active: dev
  main:
    web-application-type: none
  application:
    name: soccerbee-batch
  batch:
    initialize-schema: always
    job:
      enabled: true
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate.format_sql: false    
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://soccerbee-dev-v2.cidy7xazjee0.ap-northeast-2.rds.amazonaws.com:3306/soccerbee?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: soccerbee
    password: dbqltmfoq00!!
      
logging:
  level:
    root: info
    org.springframework.beans: error
    org.springframework.context: error
    org.springframework.transaction: error
    org.springframework.transaction.interceptor: error
    org.springframework.web: error
    org.hibernate: error
    org.hibernate.type: error
  pattern:
    console: '%black(%d{yyyy-MM-dd HH:mm:ss}) %green(%-5level) %cyan(%-40.40logger{40}) - %msg%n'